EXE='./png2hsv'

task :build do
  sh 'go build'
end

task :bin do
  sh 'GOOS=windows GOARCH=amd64 go build'
  sh 'go build'
  mkdir_p '../bin'
  cp 'png2hsv.exe', '../bin'
  cp 'png2hsv', '../bin'
end

task :test => :build do
  Dir.glob '../../Images/*.png' do |f|
    sh EXE, f, File.basename(f)
  end
end

task :test_split => :build do
  Dir.glob '../../Images/*.png' do |f|
    next if f.match /_Light.png$/
    sh EXE, '-split', f, File.basename(f)
  end
end

task :clean do
  FileUtils.rm_rf Dir.glob('*.png')
end
